### PR TITLE
Issue #35 - fixing missing migrations parameter

### PR DESCRIPTION
**Pull request by arianmaykon**
"Fix" for issue #35

### CODE REVIEW

**Comment by ergo** [comment]
@arianmaykon Which version of mysql are you using? All the tests for 0.6.3 passed for me.

**Comment by arianmaykon** [comment]
MySQL 5.7.12.

**Comment by ergo** [comment]
Ok lets continue in https://github.com/ergo/ziggurat_foundations/issues/35#issuecomment-212008252 then.

**Comment by ergo** [comment]
Thank you - this indeed fixes the broken behavior on 5.7

**Pull request merged**
